version: "3"
volumes:
  dbbackups:
  postgis-data:

services:
  meter_project:
    build:
      context: .
    container_name: meter_project
    ports:
      - "8000:8000"
    volumes:
      - ./meter_project:/meter_project
    #command: tail -F anything
    command: bash -c "sleep 5s && python3 manage.py migrate  && python3 manage.py runserver 0.0.0.0:8000" 
    environment:  
      - DB_HOST=db
      - DB_NAME=gis
      - DB_USER=docker
      - DB_PASS=docker
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on: # when our app service depends on db
      - db
      - redis
  
  celery:
    build: .
    #command: tail -F anything
    command: celery -A meter_project beat 
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_NAME=gis
      - DB_USER=docker
      - DB_PASS=docker
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - meter_project
      - redis

  db:
    image: kartoza/postgis:13-3.1
    ports:
      - 5432:5432
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups

    environment: 
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: on-failure

  redis:
    image: "redis:6.2"
